### ISSUE TITLE
Pull to refresh functionality ?

### ISSUE THREAD

**Issue by paradisehuman** [sthewissen/Xamarin.Forms.StateSquid#14]
Hi. 
Is there any way to active loading by pulling the layout ??
If not, Could you please add this feature?

**Comment by sthewissen** [comment]
This is a feature that is built into Xamarin Forms starting with 4.4 (I believe). Look for a control named `RefreshView`.

**Comment by paradisehuman** [comment]
> This is a feature that is built into Xamarin Forms starting with 4.4 (I believe). Look for a control named `RefreshView`.

Yes, It's RefreshView but I want something like RefreshView that is activated by pulling down the layout and showing any custom view (like Skeleton loading) instead of loading indicator.

**Comment by yasmoradi** [comment]
Do not compare this fantastic library with xf's refresh view please

**Comment by sthewissen** [comment]
As much as I appreciate your comments, I don't want to copy things that are already (partially) in Xamarin.Forms itself. Enhancing `RefreshView` to become templateable is something that should be added to Xamarin.Forms (and there are already issues open for it on their GitHub). If I were to spend the effort of building it I would PR it into XF directly instead of this library :)

**Comment by philtomblin** [comment]
I came upon this as I wanted to be able to pull-to-refresh to trigger my data load, but then replace the standard XF spinner with the SquidState functionality.  For the benefit of anyone else who comes across this via internet search, I successfully achieved this by setting the RefreshView IsRefreshing binding to OneWay (see https://devblogs.microsoft.com/xamarin/refreshview-xamarin-forms/):

`<RefreshView IsRefreshing="{Binding IsBusy, Mode=OneWay}"
                         Command="{Binding LoadCommand}">`
