### ISSUE TITLE
Show state template over content

### ISSUE THREAD

**Issue by mgierlasinski** [sthewissen/Xamarin.Forms.StateSquid#3]
Hi, it would be great to have overlay functionality for the state template. It could be useful when we want to show some loading effect over page content, for example progress indicator when something is saved or refreshed. We already see the content, we just want to put notification over it to show that some activity is happening.

**Comment by sthewissen** [comment]
I believe this is already possible in the current setup. Because the content of your `StateView` can be pretty much anything you can create your own overlay quite simply by wrapping your elements in `Grid` and adding a loading template with `FillAndExpand` as the vertical and horizontal option. Seeing as how pretty much anything can be put into the loading template it could be tricky to simply add a boolean and make it work in any scenario.
